steps:
- name: 'gcr.io/cloud-builders/docker'
  id: 'Build train container image'
  args: [
    'build',
    '.',
    '-t',
    'us-central1-docker.pkg.dev/starfish-detection/registry/train',
    '-f',
    'dockerfiles/train.dockerfile'
  ]
- name: 'gcr.io/cloud-builders/docker'
  id: 'Push train container image'
  args: [
    'push',
    'us-central1-docker.pkg.dev/starfish-detection/registry/train'
  ]
- name: 'gcr.io/cloud-builders/docker'
  id: 'Build backend container image'
  waitFor: ['-']
  args: [
    'build',
    '.',
    '-t',
    'us-central1-docker.pkg.dev/starfish-detection/frontend-backend/backend',
    '-f',
    'dockerfiles/inference_backend.dockerfile'
  ]
- name: 'gcr.io/cloud-builders/docker'
  id: 'Push backend container image'
  waitFor: ['Build backend container image']
  args: [
    'push',
    'us-central1-docker.pkg.dev/starfish-detection/frontend-backend/backend'
  ]
- name: 'gcr.io/cloud-builders/gcloud'
  id: 'Deploy backend to Cloud Run'
  waitFor: ['Push backend container image']
  args: [
    'run',
    'deploy',
    'backend',
    '--image',
    'us-central1-docker.pkg.dev/starfish-detection/frontend-backend/backend',
    '--region',
    'us-central1',
    '--platform',
    'managed',
    '--allow-unauthenticated'
  ]
- name: 'gcr.io/cloud-builders/docker'
  id: 'Build frontend container image'
  waitFor: ['-']
  args: [
    'build',
    '.',
    '-t',
    'us-central1-docker.pkg.dev/starfish-detection/frontend-backend/frontend',
    '-f',
    'dockerfiles/inference_frontend.dockerfile'
  ]
- name: 'gcr.io/cloud-builders/docker'
  id: 'Push frontend container image'
  waitFor: ['Build frontend container image']
  args: [
    'push',
    'us-central1-docker.pkg.dev/starfish-detection/frontend-backend/frontend'
  ]
- name: 'gcr.io/cloud-builders/gcloud'
  id: 'Deploy frontend to Cloud Run'
  waitFor: ['Push frontend container image']
  args: [
    'run',
    'deploy',
    'frontend',
    '--image',
    'us-central1-docker.pkg.dev/starfish-detection/frontend-backend/frontend',
    '--region',
    'us-central1',
    '--platform',
    'managed',
    '--allow-unauthenticated'
  ]
options:
  env:
    - DOCKER_BUILDKIT=1
  logging: CLOUD_LOGGING_ONLY
