steps:
- name: 'alpine'
  id: "Replace values in the training config"
  entrypoint: "sh"
  args:
    - '-c'
    - |
      apk add --no-cache gettext
      envsubst < configs/vertex_ai_config.yaml > config.yaml.tmp
      mv config.yaml.tmp configs/vertex_ai_config.yaml
  secretEnv: ['WANDB_API_KEY']

- name: 'alpine'
  id: "Show config"
  waitFor: ['Replace values in the training config']
  entrypoint: "sh"
  args:
    - '-c'
    - |
      cat configs/vertex_ai_config.yaml

- name: 'gcr.io/cloud-builders/gcloud'
  id: 'Train on vertex AI'
  waitFor: ['Replace values in the training config']
  args: [
    'ai',
    'custom-jobs',
    'create',
    '--region',
    'us-central1',
    '--display-name',
    'train',
    '--config',
    '${_VERTEX_TRAIN_CONFIG}',
  ]
substitutions:
  _VERTEX_TRAIN_CONFIG: 'configs/vertex_ai_config.yaml'
availableSecrets:
  secretManager:
  - versionName: projects/starfish-detection/secrets/WANDB_API_KEY/versions/latest
    env: 'WANDB_API_KEY'